Update smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -365,32 +365,25 @@ jobs:
             echo "${API_URL}"
             if curl -s "${API_URL}/api/status" | grep "ok"
             then
-              echo "Failed to call backend url."
+              echo "Success to call backend url."
               exit 0
             else
-              exit 1
+              echo "Failed to call backend url."
+              # exit 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"            
             echo "${URL}" 
-            if curl -s ${URL} | grep "ok"
+            if curl -s ${URL} | grep "Welcome"
             then
-              echo "Failed to call frontend url."
-              # exit 0
-            else
+              # Change this to 0 after the job fails
               echo "Success to call frontend url."
-              # exit 1
-
-            if curl -s http://google.com
-            then
-              echo "Failed to call google url."
               exit 0
             else
-              echo "Success to call google url."
-              exit 1
-
+              echo "Failed to call frontend url."
+              # exit 1
             fi
       - destroy-environment
       - revert-migrations
